"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['minesweeptk.py']
DATA_FILES = ['bomb.gif',
 'covered.gif',
 'eight.gif',
 'five.gif',
 'flag.gif',
 'four.gif',
 'one.gif',
 'pressed.gif',
 'q_mark.gif',
 'seven.gif',
 'six.gif',
 'three.gif',
 'two.gif',
 'zero.gif']
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/gpz500/src/Minesweeper (trunk)/bomb.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
